name: Deploy orbit-frontend React App (Vite)

on:
  push:
    branches:
      - main          # Deploy to production on main branch push
  pull_request:
    branches:
      - develop       # PR to develop → run build/tests only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache node_modules for faster build
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      # ✅ Deploy & restart Nginx in a single SSH connection
      - name: Deploy & Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22205
          script: |
            echo "🔹 Ensuring target folder exists..."
            mkdir -p /var/www/html/orbit-frontend
            echo "🔹 Cleaning old files..."
            rm -rf /var/www/html/orbit-frontend/*
            echo "🔹 Copying new build files..."
            scp -P 22205 -r /github/workspace/dist ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/orbit-frontend/
            echo "🔹 Restarting Nginx..."
            sudo systemctl restart nginx
            echo "✅ Deploy completed successfully!"
